In [5]:
# 필요 패키지
import selenium
from selenium import webdriver
import pandas as pd
from bs4 import BeautifulSoup
import numpy as np
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
from tqdm import tqdm_notebook
import time

In [1]:
date_list = []
for y in range(2018, 2023):
    start_month = 1
    end_month = 13
    if y == 2022:
        end_month = 4
    for m in range(start_month, end_month):
        if len(str(m)) == 1:
            m = '0' + str(m)
        date_list.append(str(y) + '-' + str(m))
date_list

['2018-01',
 '2018-02',
 '2018-03',
 '2018-04',
 '2018-05',
 '2018-06',
 '2018-07',
 '2018-08',
 '2018-09',
 '2018-10',
 '2018-11',
 '2018-12',
 '2019-01',
 '2019-02',
 '2019-03',
 '2019-04',
 '2019-05',
 '2019-06',
 '2019-07',
 '2019-08',
 '2019-09',
 '2019-10',
 '2019-11',
 '2019-12',
 '2020-01',
 '2020-02',
 '2020-03',
 '2020-04',
 '2020-05',
 '2020-06',
 '2020-07',
 '2020-08',
 '2020-09',
 '2020-10',
 '2020-11',
 '2020-12',
 '2021-01',
 '2021-02',
 '2021-03',
 '2021-04',
 '2021-05',
 '2021-06',
 '2021-07',
 '2021-08',
 '2021-09',
 '2021-10',
 '2021-11',
 '2021-12',
 '2022-01',
 '2022-02',
 '2022-03']

In [2]:
area_country = [['미주','미국'], ['유럽','독일'], ['유럽','프랑스'], ['유럽','이탈리아'], ['유럽','러시아'], ['중국','중국'], ['아시아','베트남'], ['아시아','싱가포르'], ['아시아','말레이시아'], ['일본', '일본'], ['아시아', '홍콩']]

In [3]:
url = 'https://www.airportal.go.kr/knowledge/statsnew/air/area.jsp#'

In [6]:
driver = webdriver.Chrome('./driver/chromedriver')
driver.get(url)

C:\Users\Jun\AppData\Local\Temp\ipykernel_8712\766079133.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome('./driver/chromedriver')

In [7]:
res = []
for s in area_country:
    for date in date_list:
        # 시작 연도 선택
        xpath = '//*[@id="start_year"]'
        start_year = Select(driver.find_element(By.XPATH,xpath))
        start_year.select_by_visible_text(str(int(date[0:4])))
        # 시작 월 선택
        xpath = '//*[@id="start_month"]'
        start_month = Select(driver.find_element(By.XPATH,xpath))
        start_month.select_by_visible_text(str(int(date[5:7])))

        # 끝 연도 선택
        xpath = '//*[@id="end_year"]'
        end_year = Select(driver.find_element(By.XPATH,xpath))
        end_year.select_by_visible_text(str(int(date[0:4])))
        # 끝 월 선택
        xpath = '//*[@id="end_month"]'
        end_month = Select(driver.find_element(By.XPATH,xpath))
        end_month.select_by_visible_text(str(int(date[5:7])))

        # 지역 선택
        xpath = '//*[@id="areaGubun"]'
        area = Select(driver.find_element(By.XPATH,xpath))
        area.select_by_visible_text(s[0])

        # 국가 선택
        xpath = '//*[@id="nationGubun"]'
        area = Select(driver.find_element(By.XPATH,xpath))
        area.select_by_visible_text(s[1])

        # 조회버튼 클릭
        xpath = '//*[@id="realContents"]/div/div[2]/div[1]/div[1]/a[2]'
        submit = driver.find_element(By.XPATH, xpath)
        driver.execute_script('arguments[0].click();',submit)
        
        time.sleep(0.5)

        # 값 가져오기
        xpath = '//*[@id="mySheet-table"]/tbody/tr[3]/td/div/div[1]/table/tbody/tr[2]/td[6]/b/span'
        value = driver.find_element(By.XPATH, xpath)
        res.append([date, s[0], s[1], value.text])

In [8]:
res

[['2018-01', '미주', '미국', '54,339'],
 ['2018-02', '미주', '미국', '46,270'],
 ['2018-03', '미주', '미국', '57,069'],
 ['2018-04', '미주', '미국', '55,639'],
 ['2018-05', '미주', '미국', '58,745'],
 ['2018-06', '미주', '미국', '60,077'],
 ['2018-07', '미주', '미국', '64,079'],
 ['2018-08', '미주', '미국', '59,088'],
 ['2018-09', '미주', '미국', '56,577'],
 ['2018-10', '미주', '미국', '60,402'],
 ['2018-11', '미주', '미국', '58,952'],
 ['2018-12', '미주', '미국', '56,195'],
 ['2019-01', '미주', '미국', '50,415'],
 ['2019-02', '미주', '미국', '43,868'],
 ['2019-03', '미주', '미국', '56,073'],
 ['2019-04', '미주', '미국', '52,819'],
 ['2019-05', '미주', '미국', '55,228'],
 ['2019-06', '미주', '미국', '58,301'],
 ['2019-07', '미주', '미국', '59,325'],
 ['2019-08', '미주', '미국', '56,513'],
 ['2019-09', '미주', '미국', '51,911'],
 ['2019-10', '미주', '미국', '56,901'],
 ['2019-11', '미주', '미국', '56,471'],
 ['2019-12', '미주', '미국', '54,869'],
 ['2020-01', '미주', '미국', '50,883'],
 ['2020-02', '미주', '미국', '47,326'],
 ['2020-03', '미주', '미국', '53,208'],
 ['2020-04', '미주', '미국', '47,042'],
 ['2020-05', '미주', '미국', '54,248'],
 ['2020-06', '미주', '미국', '53,228'],
 ['2020-07', '미주', '미국', '57,475'],
 ['2020-08', '미주', '미국', '55,963'],
 ['2020-09', '미주', '미국', '57,417'],
 ['2020-10', '미주', '미국', '62,205'],
 ['2020-11', '미주', '미국', '60,339'],
 ['2020-12', '미주', '미국', '60,937'],
 ['2021-01', '미주', '미국', '57,316'],
 ['2021-02', '미주', '미국', '56,951'],
 ['2021-03', '미주', '미국', '67,916'],
 ['2021-04', '미주', '미국', '68,522'],
 ['2021-05', '미주', '미국', '75,215'],
 ['2021-06', '미주', '미국', '73,746'],
 ['2021-07', '미주', '미국', '76,726'],
 ['2021-08', '미주', '미국', '75,521'],
 ['2021-09', '미주', '미국', '73,517'],
 ['2021-10', '미주', '미국', '73,053'],
 ['2021-11', '미주', '미국', '71,877'],
 ['2021-12', '미주', '미국', '74,757'],
 ['2022-01', '미주', '미국', '71,402'],
 ['2022-02', '미주', '미국', '60,823'],
 ['2022-03', '미주', '미국', '73,228'],
 ['2018-01', '유럽', '독일', '12,656'],
 ['2018-02', '유럽', '독일', '13,103'],
 ['2018-03', '유럽', '독일', '15,351'],
 ['2018-04', '유럽', '독일', '13,798'],
 ['2018-05', '유럽', '독일', '13,267'],
 ['2018-06', '유럽', '독일', '13,127'],
 ['2018-07', '유럽', '독일', '13,301'],
 ['2018-08', '유럽', '독일', '12,756'],
 ['2018-09', '유럽', '독일', '13,600'],
 ['2018-10', '유럽', '독일', '14,998'],
 ['2018-11', '유럽', '독일', '16,052'],
 ['2018-12', '유럽', '독일', '14,553'],
 ['2019-01', '유럽', '독일', '12,285'],
 ['2019-02', '유럽', '독일', '11,517'],
 ['2019-03', '유럽', '독일', '14,580'],
 ['2019-04', '유럽', '독일', '13,083'],
 ['2019-05', '유럽', '독일', '12,840'],
 ['2019-06', '유럽', '독일', '11,943'],
 ['2019-07', '유럽', '독일', '12,210'],
 ['2019-08', '유럽', '독일', '11,667'],
 ['2019-09', '유럽', '독일', '12,675'],
 ['2019-10', '유럽', '독일', '14,271'],
 ['2019-11', '유럽', '독일', '14,547'],
 ['2019-12', '유럽', '독일', '13,502'],
 ['2020-01', '유럽', '독일', '12,405'],
 ['2020-02', '유럽', '독일', '13,280'],
 ['2020-03', '유럽', '독일', '15,118'],
 ['2020-04', '유럽', '독일', '14,949'],
 ['2020-05', '유럽', '독일', '14,145'],
 ['2020-06', '유럽', '독일', '12,576'],
 ['2020-07', '유럽', '독일', '12,533'],
 ['2020-08', '유럽', '독일', '11,403'],
 ['2020-09', '유럽', '독일', '12,233'],
 ['2020-10', '유럽', '독일', '13,732'],
 ['2020-11', '유럽', '독일', '14,779'],
 ['2020-12', '유럽', '독일', '15,677'],
 ['2021-01', '유럽', '독일', '14,295'],
 ['2021-02', '유럽', '독일', '13,667'],
 ['2021-03', '유럽', '독일', '15,834'],
 ['2021-04', '유럽', '독일', '14,611'],
 ['2021-05', '유럽', '독일', '14,464'],
 ['2021-06', '유럽', '독일', '13,786'],
 ['2021-07', '유럽', '독일', '14,076'],
 ['2021-08', '유럽', '독일', '13,430'],
 ['2021-09', '유럽', '독일', '14,011'],
 ['2021-10', '유럽', '독일', '15,516'],
 ['2021-11', '유럽', '독일', '14,781'],
 ['2021-12', '유럽', '독일', '15,057'],
 ['2022-01', '유럽', '독일', '14,827'],
 ['2022-02', '유럽', '독일', '13,159'],
 ['2022-03', '유럽', '독일', '16,498'],
 ['2018-01', '유럽', '프랑스', '3,345'],
 ['2018-02', '유럽', '프랑스', '3,064'],
 ['2018-03', '유럽', '프랑스', '3,491'],
 ['2018-04', '유럽', '프랑스', '3,590'],
 ['2018-05', '유럽', '프랑스', '3,916'],
 ['2018-06', '유럽', '프랑스', '4,314'],
 ['2018-07', '유럽', '프랑스', '4,371'],
 ['2018-08', '유럽', '프랑스', '4,177'],
 ['2018-09', '유럽', '프랑스', '4,366'],
 ['2018-10', '유럽', '프랑스', '4,308'],
 ['2018-11', '유럽', '프랑스', '3,344'],
 ['2018-12', '유럽', '프랑스', '3,501'],
 ['2019-01', '유럽', '프랑스', '2,806'],
 ['2019-02', '유럽', '프랑스', '2,556'],
 ['2019-03', '유럽', '프랑스', '3,013'],
 ['2019-04', '유럽', '프랑스', '3,258'],
 ['2019-05', '유럽', '프랑스', '3,640'],
 ['2019-06', '유럽', '프랑스', '3,784'],
 ['2019-07', '유럽', '프랑스', '3,930'],
 ['2019-08', '유럽', '프랑스', '3,718'],
 ['2019-09', '유럽', '프랑스', '3,812'],
 ['2019-10', '유럽', '프랑스', '3,665'],
 ['2019-11', '유럽', '프랑스', '3,356'],
 ['2019-12', '유럽', '프랑스', '3,312'],
 ['2020-01', '유럽', '프랑스', '3,214'],
 ['2020-02', '유럽', '프랑스', '2,842'],
 ['2020-03', '유럽', '프랑스', '1,894'],
 ['2020-04', '유럽', '프랑스', '968'],
 ['2020-05', '유럽', '프랑스', '998'],
 ['2020-06', '유럽', '프랑스', '919'],
 ['2020-07', '유럽', '프랑스', '1,552'],
 ['2020-08', '유럽', '프랑스', '1,630'],
 ['2020-09', '유럽', '프랑스', '1,586'],
 ['2020-10', '유럽', '프랑스', '1,764'],
 ['2020-11', '유럽', '프랑스', '2,023'],
 ['2020-12', '유럽', '프랑스', '1,536'],
 ['2021-01', '유럽', '프랑스', '1,740'],
 ['2021-02', '유럽', '프랑스', '1,701'],
 ['2021-03', '유럽', '프랑스', '1,839'],
 ['2021-04', '유럽', '프랑스', '1,578'],
 ['2021-05', '유럽', '프랑스', '1,354'],
 ['2021-06', '유럽', '프랑스', '1,531'],
 ['2021-07', '유럽', '프랑스', '1,444'],
 ['2021-08', '유럽', '프랑스', '1,505'],
 ['2021-09', '유럽', '프랑스', '1,412'],
 ['2021-10', '유럽', '프랑스', '1,550'],
 ['2021-11', '유럽', '프랑스', '1,751'],
 ['2021-12', '유럽', '프랑스', '1,529'],
 ['2022-01', '유럽', '프랑스', '1,578'],
 ['2022-02', '유럽', '프랑스', '1,380'],
 ['2022-03', '유럽', '프랑스', '1,653'],
 ['2018-01', '유럽', '이탈리아', '3,345'],
 ['2018-02', '유럽', '이탈리아', '3,489'],
 ['2018-03', '유럽', '이탈리아', '4,119'],
 ['2018-04', '유럽', '이탈리아', '4,205'],
 ['2018-05', '유럽', '이탈리아', '4,372'],
 ['2018-06', '유럽', '이탈리아', '4,775'],
 ['2018-07', '유럽', '이탈리아', '5,010'],
 ['2018-08', '유럽', '이탈리아', '3,976'],
 ['2018-09', '유럽', '이탈리아', '4,454'],
 ['2018-10', '유럽', '이탈리아', '4,561'],
 ['2018-11', '유럽', '이탈리아', '4,454'],
 ['2018-12', '유럽', '이탈리아', '4,200'],
 ['2019-01', '유럽', '이탈리아', '3,567'],
 ['2019-02', '유럽', '이탈리아', '3,341'],
 ['2019-03', '유럽', '이탈리아', '4,159'],
 ['2019-04', '유럽', '이탈리아', '3,901'],
 ['2019-05', '유럽', '이탈리아', '4,290'],
 ['2019-06', '유럽', '이탈리아', '4,389'],
 ['2019-07', '유럽', '이탈리아', '4,805'],
 ['2019-08', '유럽', '이탈리아', '4,521'],
 ['2019-09', '유럽', '이탈리아', '4,554'],
 ['2019-10', '유럽', '이탈리아', '5,241'],
 ['2019-11', '유럽', '이탈리아', '5,116'],
 ['2019-12', '유럽', '이탈리아', '4,707'],
 ['2020-01', '유럽', '이탈리아', '3,794'],
 ['2020-02', '유럽', '이탈리아', '3,640'],
 ['2020-03', '유럽', '이탈리아', '3,695'],
 ['2020-04', '유럽', '이탈리아', '3,080'],
 ['2020-05', '유럽', '이탈리아', '3,427'],
 ['2020-06', '유럽', '이탈리아', '3,453'],
 ['2020-07', '유럽', '이탈리아', '3,285'],
 ['2020-08', '유럽', '이탈리아', '2,905'],
 ['2020-09', '유럽', '이탈리아', '2,791'],
 ['2020-10', '유럽', '이탈리아', '3,282'],
 ['2020-11', '유럽', '이탈리아', '3,622'],
 ['2020-12', '유럽', '이탈리아', '3,012'],
 ['2021-01', '유럽', '이탈리아', '2,548'],
 ['2021-02', '유럽', '이탈리아', '2,711'],
 ['2021-03', '유럽', '이탈리아', '3,849'],
 ['2021-04', '유럽', '이탈리아', '3,460'],
 ['2021-05', '유럽', '이탈리아', '3,851'],
 ['2021-06', '유럽', '이탈리아', '3,522'],
 ['2021-07', '유럽', '이탈리아', '4,341'],
 ['2021-08', '유럽', '이탈리아', '3,616'],
 ['2021-09', '유럽', '이탈리아', '3,217'],
 ['2021-10', '유럽', '이탈리아', '3,408'],
 ['2021-11', '유럽', '이탈리아', '3,435'],
 ['2021-12', '유럽', '이탈리아', '3,620'],
 ['2022-01', '유럽', '이탈리아', '3,487'],
 ['2022-02', '유럽', '이탈리아', '3,127'],
 ['2022-03', '유럽', '이탈리아', '4,196'],
 ['2018-01', '유럽', '러시아', '4,344'],
 ['2018-02', '유럽', '러시아', '4,568'],
 ['2018-03', '유럽', '러시아', '4,667'],
 ['2018-04', '유럽', '러시아', '4,833'],
 ['2018-05', '유럽', '러시아', '5,136'],
 ['2018-06', '유럽', '러시아', '5,376'],
 ['2018-07', '유럽', '러시아', '5,825'],
 ['2018-08', '유럽', '러시아', '5,875'],
 ['2018-09', '유럽', '러시아', '5,985'],
 ['2018-10', '유럽', '러시아', '5,316'],
 ['2018-11', '유럽', '러시아', '5,517'],
 ['2018-12', '유럽', '러시아', '5,233'],
 ['2019-01', '유럽', '러시아', '4,452'],
 ['2019-02', '유럽', '러시아', '4,024'],
 ['2019-03', '유럽', '러시아', '4,938'],
 ['2019-04', '유럽', '러시아', '4,780'],
 ['2019-05', '유럽', '러시아', '5,279'],
 ['2019-06', '유럽', '러시아', '6,124'],
 ['2019-07', '유럽', '러시아', '6,600'],
 ['2019-08', '유럽', '러시아', '5,856'],
 ['2019-09', '유럽', '러시아', '5,101'],
 ['2019-10', '유럽', '러시아', '4,555'],
 ['2019-11', '유럽', '러시아', '4,256'],
 ['2019-12', '유럽', '러시아', '4,141'],
 ['2020-01', '유럽', '러시아', '3,227'],
 ['2020-02', '유럽', '러시아', '3,298'],
 ['2020-03', '유럽', '러시아', '3,408'],
 ['2020-04', '유럽', '러시아', '3,040'],
 ['2020-05', '유럽', '러시아', '2,845'],
 ['2020-06', '유럽', '러시아', '3,225'],
 ['2020-07', '유럽', '러시아', '3,400'],
 ['2020-08', '유럽', '러시아', '2,830'],
 ['2020-09', '유럽', '러시아', '3,081'],
 ['2020-10', '유럽', '러시아', '3,341'],
 ['2020-11', '유럽', '러시아', '3,988'],
 ['2020-12', '유럽', '러시아', '3,533'],
 ['2021-01', '유럽', '러시아', '3,046'],
 ['2021-02', '유럽', '러시아', '3,050'],
 ['2021-03', '유럽', '러시아', '3,953'],
 ['2021-04', '유럽', '러시아', '3,668'],
 ['2021-05', '유럽', '러시아', '3,836'],
 ['2021-06', '유럽', '러시아', '3,290'],
 ['2021-07', '유럽', '러시아', '3,585'],
 ['2021-08', '유럽', '러시아', '3,388'],
 ['2021-09', '유럽', '러시아', '3,061'],
 ['2021-10', '유럽', '러시아', '3,516'],
 ['2021-11', '유럽', '러시아', '3,353'],
 ['2021-12', '유럽', '러시아', '3,802'],
 ['2022-01', '유럽', '러시아', '3,388'],
 ['2022-02', '유럽', '러시아', '3,604'],
 ['2022-03', '유럽', '러시아', '391'],
 ['2018-01', '중국', '중국', '61,175'],
 ['2018-02', '중국', '중국', '51,183'],
 ['2018-03', '중국', '중국', '65,345'],
 ['2018-04', '중국', '중국', '63,762'],
 ['2018-05', '중국', '중국', '64,102'],
 ['2018-06', '중국', '중국', '61,732'],
 ['2018-07', '중국', '중국', '62,878'],
 ['2018-08', '중국', '중국', '67,085'],
 ['2018-09', '중국', '중국', '67,221'],
 ['2018-10', '중국', '중국', '68,059'],
 ['2018-11', '중국', '중국', '66,347'],
 ['2018-12', '중국', '중국', '62,245'],
 ['2019-01', '중국', '중국', '58,542'],
 ['2019-02', '중국', '중국', '47,402'],
 ['2019-03', '중국', '중국', '62,280'],
 ['2019-04', '중국', '중국', '59,677'],
 ['2019-05', '중국', '중국', '60,576'],
 ['2019-06', '중국', '중국', '61,215'],
 ['2019-07', '중국', '중국', '61,286'],
 ['2019-08', '중국', '중국', '66,644'],
 ['2019-09', '중국', '중국', '66,770'],
 ['2019-10', '중국', '중국', '70,531'],
 ['2019-11', '중국', '중국', '70,667'],
 ['2019-12', '중국', '중국', '68,109'],
 ['2020-01', '중국', '중국', '61,373'],
 ['2020-02', '중국', '중국', '45,509'],
 ['2020-03', '중국', '중국', '49,043'],
 ['2020-04', '중국', '중국', '44,522'],
 ['2020-05', '중국', '중국', '44,699'],
 ['2020-06', '중국', '중국', '41,292'],
 ['2020-07', '중국', '중국', '44,137'],
 ['2020-08', '중국', '중국', '42,555'],
 ['2020-09', '중국', '중국', '49,885'],
 ['2020-10', '중국', '중국', '47,035'],
 ['2020-11', '중국', '중국', '49,034'],
 ['2020-12', '중국', '중국', '51,819'],
 ['2021-01', '중국', '중국', '50,138'],
 ['2021-02', '중국', '중국', '41,705'],
 ['2021-03', '중국', '중국', '52,430'],
 ['2021-04', '중국', '중국', '51,006'],
 ['2021-05', '중국', '중국', '50,511'],
 ['2021-06', '중국', '중국', '48,615'],
 ['2021-07', '중국', '중국', '50,990'],
 ['2021-08', '중국', '중국', '49,385'],
 ['2021-09', '중국', '중국', '52,578'],
 ['2021-10', '중국', '중국', '50,250'],
 ['2021-11', '중국', '중국', '50,296'],
 ['2021-12', '중국', '중국', '50,865'],
 ['2022-01', '중국', '중국', '46,472'],
 ['2022-02', '중국', '중국', '40,657'],
 ['2022-03', '중국', '중국', '48,055'],
 ['2018-01', '아시아', '베트남', '27,635'],
 ['2018-02', '아시아', '베트남', '20,753'],
 ['2018-03', '아시아', '베트남', '27,038'],
 ['2018-04', '아시아', '베트남', '24,464'],
 ['2018-05', '아시아', '베트남', '23,555'],
 ['2018-06', '아시아', '베트남', '24,014'],
 ['2018-07', '아시아', '베트남', '25,783'],
 ['2018-08', '아시아', '베트남', '26,959'],
 ['2018-09', '아시아', '베트남', '26,209'],
 ['2018-10', '아시아', '베트남', '28,758'],
 ['2018-11', '아시아', '베트남', '26,916'],
 ['2018-12', '아시아', '베트남', '26,767'],
 ['2019-01', '아시아', '베트남', '29,900'],
 ['2019-02', '아시아', '베트남', '23,883'],
 ['2019-03', '아시아', '베트남', '31,069'],
 ['2019-04', '아시아', '베트남', '27,511'],
 ['2019-05', '아시아', '베트남', '26,569'],
 ['2019-06', '아시아', '베트남', '26,673'],
 ['2019-07', '아시아', '베트남', '29,644'],
 ['2019-08', '아시아', '베트남', '29,597'],
 ['2019-09', '아시아', '베트남', '28,030'],
 ['2019-10', '아시아', '베트남', '29,853'],
 ['2019-11', '아시아', '베트남', '27,159'],
 ['2019-12', '아시아', '베트남', '28,500'],
 ['2020-01', '아시아', '베트남', '28,494'],
 ['2020-02', '아시아', '베트남', '25,583'],
 ['2020-03', '아시아', '베트남', '15,285'],
 ['2020-04', '아시아', '베트남', '11,186'],
 ['2020-05', '아시아', '베트남', '11,473'],
 ['2020-06', '아시아', '베트남', '15,461'],
 ['2020-07', '아시아', '베트남', '17,841'],
 ['2020-08', '아시아', '베트남', '17,750'],
 ['2020-09', '아시아', '베트남', '19,876'],
 ['2020-10', '아시아', '베트남', '20,468'],
 ['2020-11', '아시아', '베트남', '18,196'],
 ['2020-12', '아시아', '베트남', '20,709'],
 ['2021-01', '아시아', '베트남', '20,824'],
 ['2021-02', '아시아', '베트남', '14,855'],
 ['2021-03', '아시아', '베트남', '20,991'],
 ['2021-04', '아시아', '베트남', '20,281'],
 ['2021-05', '아시아', '베트남', '18,934'],
 ['2021-06', '아시아', '베트남', '19,530'],
 ['2021-07', '아시아', '베트남', '21,273'],
 ['2021-08', '아시아', '베트남', '19,240'],
 ['2021-09', '아시아', '베트남', '19,670'],
 ['2021-10', '아시아', '베트남', '21,561'],
 ['2021-11', '아시아', '베트남', '21,727'],
 ['2021-12', '아시아', '베트남', '23,985'],
 ['2022-01', '아시아', '베트남', '23,094'],
 ['2022-02', '아시아', '베트남', '16,777'],
 ['2022-03', '아시아', '베트남', '24,235'],
 ['2018-01', '아시아', '싱가포르', '9,262'],
 ['2018-02', '아시아', '싱가포르', '8,205'],
 ['2018-03', '아시아', '싱가포르', '10,158'],
 ['2018-04', '아시아', '싱가포르', '9,933'],
 ['2018-05', '아시아', '싱가포르', '9,431'],
 ['2018-06', '아시아', '싱가포르', '8,860'],
 ['2018-07', '아시아', '싱가포르', '9,819'],
 ['2018-08', '아시아', '싱가포르', '9,093'],
 ['2018-09', '아시아', '싱가포르', '9,428'],
 ['2018-10', '아시아', '싱가포르', '9,689'],
 ['2018-11', '아시아', '싱가포르', '9,600'],
 ['2018-12', '아시아', '싱가포르', '10,057'],
 ['2019-01', '아시아', '싱가포르', '9,720'],
 ['2019-02', '아시아', '싱가포르', '8,145'],
 ['2019-03', '아시아', '싱가포르', '10,530'],
 ['2019-04', '아시아', '싱가포르', '9,947'],
 ['2019-05', '아시아', '싱가포르', '9,520'],
 ['2019-06', '아시아', '싱가포르', '9,309'],
 ['2019-07', '아시아', '싱가포르', '9,013'],
 ['2019-08', '아시아', '싱가포르', '9,907'],
 ['2019-09', '아시아', '싱가포르', '9,512'],
 ['2019-10', '아시아', '싱가포르', '10,892'],
 ['2019-11', '아시아', '싱가포르', '10,417'],
 ['2019-12', '아시아', '싱가포르', '10,918'],
 ['2020-01', '아시아', '싱가포르', '9,911'],
 ['2020-02', '아시아', '싱가포르', '9,220'],
 ['2020-03', '아시아', '싱가포르', '6,107'],
 ['2020-04', '아시아', '싱가포르', '7,186'],
 ['2020-05', '아시아', '싱가포르', '5,999'],
 ['2020-06', '아시아', '싱가포르', '5,303'],
 ['2020-07', '아시아', '싱가포르', '6,953'],
 ['2020-08', '아시아', '싱가포르', '6,883'],
 ['2020-09', '아시아', '싱가포르', '6,498'],
 ['2020-10', '아시아', '싱가포르', '6,754'],
 ['2020-11', '아시아', '싱가포르', '7,294'],
 ['2020-12', '아시아', '싱가포르', '7,853'],
 ['2021-01', '아시아', '싱가포르', '8,140'],
 ['2021-02', '아시아', '싱가포르', '7,173'],
 ['2021-03', '아시아', '싱가포르', '8,301'],
 ['2021-04', '아시아', '싱가포르', '8,554'],
 ['2021-05', '아시아', '싱가포르', '8,233'],
 ['2021-06', '아시아', '싱가포르', '8,778'],
 ['2021-07', '아시아', '싱가포르', '8,077'],
 ['2021-08', '아시아', '싱가포르', '6,664'],
 ['2021-09', '아시아', '싱가포르', '7,568'],
 ['2021-10', '아시아', '싱가포르', '8,241'],
 ['2021-11', '아시아', '싱가포르', '8,230'],
 ['2021-12', '아시아', '싱가포르', '7,468'],
 ['2022-01', '아시아', '싱가포르', '7,797'],
 ['2022-02', '아시아', '싱가포르', '6,754'],
 ['2022-03', '아시아', '싱가포르', '7,920'],
 ['2018-01', '아시아', '말레이시아', '7,541'],
 ['2018-02', '아시아', '말레이시아', '6,381'],
 ['2018-03', '아시아', '말레이시아', '7,608'],
 ['2018-04', '아시아', '말레이시아', '6,988'],
 ['2018-05', '아시아', '말레이시아', '6,672'],
 ['2018-06', '아시아', '말레이시아', '6,598'],
 ['2018-07', '아시아', '말레이시아', '6,817'],
 ['2018-08', '아시아', '말레이시아', '7,414'],
 ['2018-09', '아시아', '말레이시아', '6,898'],
 ['2018-10', '아시아', '말레이시아', '7,422'],
 ['2018-11', '아시아', '말레이시아', '7,517'],
 ['2018-12', '아시아', '말레이시아', '7,752'],
 ['2019-01', '아시아', '말레이시아', '7,268'],
 ['2019-02', '아시아', '말레이시아', '6,460'],
 ['2019-03', '아시아', '말레이시아', '7,462'],
 ['2019-04', '아시아', '말레이시아', '6,737'],
 ['2019-05', '아시아', '말레이시아', '6,259'],
 ['2019-06', '아시아', '말레이시아', '6,149'],
 ['2019-07', '아시아', '말레이시아', '6,771'],
 ['2019-08', '아시아', '말레이시아', '7,313'],
 ['2019-09', '아시아', '말레이시아', '6,493'],
 ['2019-10', '아시아', '말레이시아', '6,908'],
 ['2019-11', '아시아', '말레이시아', '7,314'],
 ['2019-12', '아시아', '말레이시아', '7,824'],
 ['2020-01', '아시아', '말레이시아', '7,442'],
 ['2020-02', '아시아', '말레이시아', '7,496'],
 ['2020-03', '아시아', '말레이시아', '4,711'],
 ['2020-04', '아시아', '말레이시아', '4,014'],
 ['2020-05', '아시아', '말레이시아', '4,000'],
 ['2020-06', '아시아', '말레이시아', '4,207'],
 ['2020-07', '아시아', '말레이시아', '5,373'],
 ['2020-08', '아시아', '말레이시아', '4,709'],
 ['2020-09', '아시아', '말레이시아', '4,668'],
 ['2020-10', '아시아', '말레이시아', '5,313'],
 ['2020-11', '아시아', '말레이시아', '5,016'],
 ['2020-12', '아시아', '말레이시아', '5,517'],
 ['2021-01', '아시아', '말레이시아', '6,129'],
 ['2021-02', '아시아', '말레이시아', '5,600'],
 ['2021-03', '아시아', '말레이시아', '6,500'],
 ['2021-04', '아시아', '말레이시아', '6,326'],
 ['2021-05', '아시아', '말레이시아', '6,078'],
 ['2021-06', '아시아', '말레이시아', '6,337'],
 ['2021-07', '아시아', '말레이시아', '5,903'],
 ['2021-08', '아시아', '말레이시아', '6,126'],
 ['2021-09', '아시아', '말레이시아', '6,815'],
 ['2021-10', '아시아', '말레이시아', '7,248'],
 ['2021-11', '아시아', '말레이시아', '6,232'],
 ['2021-12', '아시아', '말레이시아', '6,354'],
 ['2022-01', '아시아', '말레이시아', '5,438'],
 ['2022-02', '아시아', '말레이시아', '5,419'],
 ['2022-03', '아시아', '말레이시아', '6,465'],
 ['2018-01', '일본', '일본', '45,067'],
 ['2018-02', '일본', '일본', '44,147'],
 ['2018-03', '일본', '일본', '50,123'],
 ['2018-04', '일본', '일본', '46,022'],
 ['2018-05', '일본', '일본', '43,042'],
 ['2018-06', '일본', '일본', '43,273'],
 ['2018-07', '일본', '일본', '42,816'],
 ['2018-08', '일본', '일본', '43,946'],
 ['2018-09', '일본', '일본', '42,776'],
 ['2018-10', '일본', '일본', '46,869'],
 ['2018-11', '일본', '일본', '45,832'],
 ['2018-12', '일본', '일본', '45,913'],
 ['2019-01', '일본', '일본', '42,544'],
 ['2019-02', '일본', '일본', '39,547'],
 ['2019-03', '일본', '일본', '44,840'],
 ['2019-04', '일본', '일본', '40,587'],
 ['2019-05', '일본', '일본', '37,776'],
 ['2019-06', '일본', '일본', '38,046'],
 ['2019-07', '일본', '일본', '37,671'],
 ['2019-08', '일본', '일본', '35,607'],
 ['2019-09', '일본', '일본', '31,352'],
 ['2019-10', '일본', '일본', '32,236'],
 ['2019-11', '일본', '일본', '32,764'],
 ['2019-12', '일본', '일본', '33,626'],
 ['2020-01', '일본', '일본', '30,786'],
 ['2020-02', '일본', '일본', '29,626'],
 ['2020-03', '일본', '일본', '22,728'],
 ['2020-04', '일본', '일본', '23,090'],
 ['2020-05', '일본', '일본', '18,679'],
 ['2020-06', '일본', '일본', '18,881'],
 ['2020-07', '일본', '일본', '20,282'],
 ['2020-08', '일본', '일본', '20,154'],
 ['2020-09', '일본', '일본', '22,398'],
 ['2020-10', '일본', '일본', '24,646'],
 ['2020-11', '일본', '일본', '25,157'],
 ['2020-12', '일본', '일본', '27,143'],
 ['2021-01', '일본', '일본', '25,473'],
 ['2021-02', '일본', '일본', '26,069'],
 ['2021-03', '일본', '일본', '29,710'],
 ['2021-04', '일본', '일본', '28,489'],
 ['2021-05', '일본', '일본', '25,016'],
 ['2021-06', '일본', '일본', '26,447'],
 ['2021-07', '일본', '일본', '26,708'],
 ['2021-08', '일본', '일본', '25,228'],
 ['2021-09', '일본', '일본', '28,038'],
 ['2021-10', '일본', '일본', '26,400'],
 ['2021-11', '일본', '일본', '24,975'],
 ['2021-12', '일본', '일본', '26,157'],
 ['2022-01', '일본', '일본', '21,677'],
 ['2022-02', '일본', '일본', '23,682'],
 ['2022-03', '일본', '일본', '28,276'],
 ['2018-01', '아시아', '홍콩', '24,325'],
 ['2018-02', '아시아', '홍콩', '19,599'],
 ['2018-03', '아시아', '홍콩', '24,852'],
 ['2018-04', '아시아', '홍콩', '24,472'],
 ['2018-05', '아시아', '홍콩', '25,089'],
 ['2018-06', '아시아', '홍콩', '24,174'],
 ['2018-07', '아시아', '홍콩', '24,676'],
 ['2018-08', '아시아', '홍콩', '26,162'],
 ['2018-09', '아시아', '홍콩', '25,644'],
 ['2018-10', '아시아', '홍콩', '26,236'],
 ['2018-11', '아시아', '홍콩', '26,343'],
 ['2018-12', '아시아', '홍콩', '25,789'],
 ['2019-01', '아시아', '홍콩', '23,529'],
 ['2019-02', '아시아', '홍콩', '17,941'],
 ['2019-03', '아시아', '홍콩', '24,633'],
 ['2019-04', '아시아', '홍콩', '23,726'],
 ['2019-05', '아시아', '홍콩', '23,564'],
 ['2019-06', '아시아', '홍콩', '22,698'],
 ['2019-07', '아시아', '홍콩', '22,998'],
 ['2019-08', '아시아', '홍콩', '22,960'],
 ['2019-09', '아시아', '홍콩', '22,394'],
 ['2019-10', '아시아', '홍콩', '24,474'],
 ['2019-11', '아시아', '홍콩', '24,749'],
 ['2019-12', '아시아', '홍콩', '25,347'],
 ['2020-01', '아시아', '홍콩', '21,333'],
 ['2020-02', '아시아', '홍콩', '17,792'],
 ['2020-03', '아시아', '홍콩', '20,307'],
 ['2020-04', '아시아', '홍콩', '18,915'],
 ['2020-05', '아시아', '홍콩', '18,753'],
 ['2020-06', '아시아', '홍콩', '17,643'],
 ['2020-07', '아시아', '홍콩', '21,565'],
 ['2020-08', '아시아', '홍콩', '22,218'],
 ['2020-09', '아시아', '홍콩', '23,166'],

In [9]:
df_fin = pd.DataFrame(res)

In [10]:
df_fin.rename(columns={0:'년월', 1:'지역', 2:'국가명', 3:'화물(톤)'}, inplace=True)

In [11]:
df_fin

          년월   지역 국가명   화물(톤)
0    2018-01   미주  미국  54,339
1    2018-02   미주  미국  46,270
2    2018-03   미주  미국  57,069
3    2018-04   미주  미국  55,639
4    2018-05   미주  미국  58,745
..       ...  ...  ..     ...
556  2021-11  아시아  홍콩  22,802
557  2021-12  아시아  홍콩  23,061
558  2022-01  아시아  홍콩  22,739
559  2022-02  아시아  홍콩  16,623
560  2022-03  아시아  홍콩  20,440

[561 rows x 4 columns]

In [12]:
df_fin['지역'] = df_fin['지역'].replace(['중국'],'아시아')

In [13]:
df_fin['지역'] = df_fin['지역'].replace(['일본'],'아시아')

In [14]:
df_fin.loc[df_fin['국가명'] == '일본']

          년월   지역 국가명   화물(톤)
459  2018-01  아시아  일본  45,067
460  2018-02  아시아  일본  44,147
461  2018-03  아시아  일본  50,123
462  2018-04  아시아  일본  46,022
463  2018-05  아시아  일본  43,042
464  2018-06  아시아  일본  43,273
465  2018-07  아시아  일본  42,816
466  2018-08  아시아  일본  43,946
467  2018-09  아시아  일본  42,776
468  2018-10  아시아  일본  46,869
469  2018-11  아시아  일본  45,832
470  2018-12  아시아  일본  45,913
471  2019-01  아시아  일본  42,544
472  2019-02  아시아  일본  39,547
473  2019-03  아시아  일본  44,840
474  2019-04  아시아  일본  40,587
475  2019-05  아시아  일본  37,776
476  2019-06  아시아  일본  38,046
477  2019-07  아시아  일본  37,671
478  2019-08  아시아  일본  35,607
479  2019-09  아시아  일본  31,352
480  2019-10  아시아  일본  32,236
481  2019-11  아시아  일본  32,764
482  2019-12  아시아  일본  33,626
483  2020-01  아시아  일본  30,786
484  2020-02  아시아  일본  29,626
485  2020-03  아시아  일본  22,728
486  2020-04  아시아  일본  23,090
487  2020-05  아시아  일본  18,679
488  2020-06  아시아  일본  18,881
489  2020-07  아시아  일본  20,282
490  2020-08  아시아  일본  20,154
491  2020-09  아시아  일본  22,398
492  2020-10  아시아  일본  24,646
493  2020-11  아시아  일본  25,157
494  2020-12  아시아  일본  27,143
495  2021-01  아시아  일본  25,473
496  2021-02  아시아  일본  26,069
497  2021-03  아시아  일본  29,710
498  2021-04  아시아  일본  28,489
499  2021-05  아시아  일본  25,016
500  2021-06  아시아  일본  26,447
501  2021-07  아시아  일본  26,708
502  2021-08  아시아  일본  25,228
503  2021-09  아시아  일본  28,038
504  2021-10  아시아  일본  26,400
505  2021-11  아시아  일본  24,975
506  2021-12  아시아  일본  26,157
507  2022-01  아시아  일본  21,677
508  2022-02  아시아  일본  23,682
509  2022-03  아시아  일본  28,276

In [15]:
tmp = df_fin['화물(톤)']
tmp

0      54,339
1      46,270
2      57,069
3      55,639
4      58,745
        ...
556    22,802
557    23,061
558    22,739
559    16,623
560    20,440
Name: 화물(톤), Length: 561, dtype: object

In [16]:
for i in range(0, len(tmp)):
    tmp[i] = tmp[i].replace(',','')
    tmp[i] = int(tmp[i])

In [17]:
df_fin['화물(톤)'] = tmp

In [18]:
df_fin

          년월   지역 국가명  화물(톤)
0    2018-01   미주  미국  54339
1    2018-02   미주  미국  46270
2    2018-03   미주  미국  57069
3    2018-04   미주  미국  55639
4    2018-05   미주  미국  58745
..       ...  ...  ..    ...
556  2021-11  아시아  홍콩  22802
557  2021-12  아시아  홍콩  23061
558  2022-01  아시아  홍콩  22739
559  2022-02  아시아  홍콩  16623
560  2022-03  아시아  홍콩  20440

[561 rows x 4 columns]

In [19]:
df_fin.to_csv('./data/항공화물.csv')